version: '3.0'
services:
  mowgli-openmower:
    image: ghcr.io/mnh-jansson/mowgli-docker:main
    ports:
      - "8080:8080"
      - "1883:1883"
      - "9001:9001"
      - "9002:9002"
    volumes:
      - ./mower_params:/root/mower_params
      - ./config:/config
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
      - /dev/ttyACM0:/dev/ttyACM0
    container_name: "mowgli-openmower"
